### ISSUE TITLE
UI Epic

### ISSUE THREAD

**Issue by emranpoh** [ianfromdover/utown-green-ar#7]
- [ ] Implement Start Menu
- [ ] Implement (skippable) pages of still-image tutorial
- [ ] Implement VPS Localisation Guide
- [ ] Implement Pause Menu (can see the tutorial from here again)
- [ ] (nice to have) Implement screenshot button / mode
- [ ] Implement about page
